# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/**/Entity/*'
            - '../src/Domain/**/Enum/*'
            - '../src/Domain/**/ValueObject/*'
            - '../src/Domain/**/Trait/*'
            - '../src/Domain/**/Repository/*Interface.php'
        public: false

    App\Application\:
        resource: '../src/Application/'
        exclude:
            - '../src/Application/**/DTO/*'
        public: false

    App\Infrastructure\:
        resource: '../src/Infrastructure/'
        public: false

    App\Interface\Http\Controller\:
        resource: '../src/Interface/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\User\DoctrineUserRepository

    App\Domain\User\Repository\UserCredentialRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\User\DoctrineUserCredentialRepository
